# Generated by Django 3.0.5 on 2020-04-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=200)),
            ],
        ),
    ]
